run_analysis: true
analysis:
    filters:
        # - config.wrapper_cls_lst:
        #       - minigrid.wrappers.OneHotPartialObsWrapper
        #       - minigrid.wrappers.ImgObsWrapper
        #       - gymnasium.wrappers.FlattenObservation
        #       - emma.poi.poi_wrapper.EMMAWrapper
        - config.model_trainer._target_: emma.envs.color_door_key.CorrectKeyDistancePredictor
        - config.emma_wrapper_kwargs.include_task_reward: null
        - config.model_trainer.epochs_per_rollout: null
    load_from_output_dir: true
device: mps
defaults:
    - kp_no_poi
    - _self_
