experiment_name: emma_experiment
n_runs: 1
n_envs: 10
n_run_method: series
seed: 0
wandb:
    project: emma
    mode: disabled
env_config:
    env_id: emma.envs.color_door_key.ColoredDoorKeyEnv
    door_color: red
    correct_key_color:
        - red
        - blue
    key_colors:
        - [red, blue]
wrapper_cls_lst:
    - minigrid.wrappers.ImgObsWrapper
total_time_steps: 5000000
transfer_steps:
    - 2000000
log: true
save_model: true
record_policy_videos: true
video_freq: 100000
video_length: 200
defaults:
    - rl_config
    - _self_
