experiment_name: emma_experiment
n_runs: 10
n_envs: 10
n_run_method: series
seed: 0
wandb:
    project: emma
    # mode: disabled
env_config:
    env_id: emma.envs.color_door_key.ColoredDoorKeyEnv
    door_color: red
    correct_key_color:
        - red
        - blue
    key_colors:
        - [red, blue]
model_cls: emma.poi_exploration.POIAgnosticPPO
model_kwargs:
    learning_rate: 0.001
    n_steps: 2048
    batch_size: 256
    n_epochs: 4
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.2
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 0.5
wrapper_cls_lst:
    - minigrid.wrappers.ImgObsWrapper
callback_cls_lst:
    - emma.external_model.ExternalModelTrainerCallback
callback_kwargs_lst:
    - model_trainer:
          _target_: emma.envs.color_door_key.CorrectKeyDistancePredictor
          model:
              _target_: experiment_lab.common.networks.create_mlp_network
              layer_sizes:
                  - 147
                  - 50
                  - 10
                  - 1
              layer_activations:
                  _target_: torch.nn.ReLU
              final_activation:
                  _target_: torch.nn.Sigmoid
          device: cuda
      batch_size: 64
device: cuda
total_time_steps: 8000000
transfer_steps:
    - 5000000
log: true
save_model: true
record_policy_videos: true
video_freq: 100000
video_length: 200
defaults:
    - rl_config
    - _self_
