experiment_name: disagreement_ir_emb_forward_model_door_key_change
model_cls: emma.poi.poi_exploration.POIInstrinsicRewardPPO
model_kwargs:
    beta: 10
policy_cls: stable_baselines3.ppo.MultiInputPolicy
defaults:
    - door_key_change
    - model_trainer/forward_model
    - poi_model/disagreement
    - poi_emb_learner/sampling_poi_emb
    - _self_
    - dev