experiment_name: key_prediction_door_key_change
model_trainer:
    _target_: emma.envs.color_door_key.CorrectKeyDistancePredictor
    model:
        _target_: emma.external_model.MCModule
        inner_module:
            _target_: experiment_lab.common.networks.create_mlp_network
            layer_sizes:
                - 980
                - 100
                - 10
                - 1
            layer_activations:
                _target_: torch.nn.ReLU
            final_activation:
                _target_: torch.nn.ReLU
            dropout_p: 0.5
        num_samples: 30
    batch_size: 128
defaults:
    - door_key_change
    - _self_
