experiment_name: key_prediction_door_key_change
model_cls: emma.poi.poi_exploration.POIAgnosticPPO
defaults:
    - door_key_change
    - model_trainer/key_prediction
    - poi_model/zero
    - _self_
