experiment_name: disagreement_ir_key_prediction_door_key_change
model_cls: emma.poi.poi_exploration.POIInstrinsicRewardPPO
model_kwargs:
    beta: 0.1
defaults:
    - door_key_change
    - model_trainer/key_prediction
    - poi_model/disagreement
    - _self_