experiment_name: grad_ir_key_prediction_door_key_change
poi_model:
    _target_: emma.poi.poi_field.ModelGradientPOIField
model_kwargs:
    beta: 10
defaults:
    - kp_expl_intrinsic_reward
    - _self_
