experiment_name: disagreement_diayn_key_prediction_door_key_change
model_kwargs:
    beta: 0.01
    discriminator:
        _target_: experiment_lab.common.networks.create_mlp_network
        layer_sizes:
            - ${obs_length}
            - 200
            - ${poi_emb_learner.poi_emb_size}
        layer_activations:
            _target_: torch.nn.LeakyReLU
            negative_slope: 0.01
        final_activation:
            _target_: torch.nn.Softmax
    discriminator_optimizer_cls: torch.optim.Adam
    discriminator_optimizer_kwargs: null
    discriminator_batch_size: 128
defaults:
    - kp_expl_diayn
    - poi_model/disagreement
    - _self_
