experiment_name: disagreement_ir_emb_key_prediction_door_key_change
model_cls: emma.poi.poi_exploration.POIInstrinsicRewardPPO
model_kwargs:
    beta: 0.1
policy_cls: emma.external_model.MCMultiInputActorCriticPolicy
defaults:
    - policy_model
    - poi_model/disagreement
    - poi_emb_learner/sampling_poi_emb
    - _self_
    - dev
