experiment_name: policy_door_key_change
policy_cls: emma.external_model.MCActorCriticPolicy
policy_kwargs:
    mlp_extractor_dropout_p: 0.5
    mlp_extractor_num_samples: 30
n_eval_steps: 0
defaults:
    - door_key_change
    - model_trainer/policy
    - _self_
