experiment_name: pos_prediction_door_key_change
model_cls: emma.poi.poi_exploration.POIAgnosticPPO
defaults:
    - door_key_change
    - model_trainer/position_prediction
    - poi_model/zero
    - _self_
