experiment_name: disagreement_ir_forward_model_walker
model_cls: emma.poi.poi_exploration.POIInstrinsicRewardPPO
model_kwargs:
    beta: 10
defaults:
    - walker
    - model_trainer/forward_model
    - poi_model/disagreement
    - _self_
