experiment_name: disagreement_ir_emb_policy_walker
model_cls: emma.poi.poi_exploration.POIInstrinsicRewardPPO
model_kwargs:
    beta: 0.1
policy_cls: emma.external_model.MCMultiInputActorCriticPolicy
defaults:
    - policy_model
    - poi_model/disagreement
    - poi_emb_learner/sampling_poi_emb
    - _self_
