experiment_name: disagreement_ir_policy_walker
model_cls: emma.poi.poi_exploration.POIInstrinsicRewardPPO
model_kwargs:
    beta: 0.1
defaults:
    - policy_model
    - poi_model/disagreement
    - _self_